# Managing Kleio files

> First time use: follow instructions in the [README.md](README.md) file in this directory.

This notebook is not relevant for automated testing purposes.

In [1]:
! pip install -r requirements.txt

Requirement already satisfied: timelink in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from -r requirements.txt (line 1)) (1.1.26)
Requirement already satisfied: openpyxl in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from -r requirements.txt (line 2)) (3.1.5)
Requirement already satisfied: jinja2 in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from -r requirements.txt (line 3)) (3.1.6)
Requirement already satisfied: matplotlib in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from -r requirements.txt (line 4)) (3.10.1)
Requirement already satisfied: typer in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from timelink->-r requirements.txt (line 1)) (0.15.2)
Requirement already satisfied: fastapi in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from timelink->-r requirements.txt (line 1)) (0.115.12)
Requirement already satisfied: sqlalchemy in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from timelink->-r requirements.txt (line 1)) (2.0.40)
Requirement already satisfied: sqlalchemy-utils in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from timelink->-r requirements.txt (line 1)) (0.41.2)
Requirement already satisfied: alembic in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from timelink->-r requirements.txt (line 1)) (1.15.2)
Requirement already satisfied: pydantic in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from timelink->-r requirements.txt (line 1)) (2.11.3)
Requirement already satisfied: pydantic-settings in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from timelink->-r requirements.txt (line 1)) (2.8.1)
Requirement already satisfied: python-dotenv in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from timelink->-r requirements.txt (line 1)) (1.1.0)
Requirement already satisfied: python-box in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from timelink->-r requirements.txt (line 1)) (7.3.2)
Requirement already satisfied: python-multipart in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from timelink->-r requirements.txt (line 1)) (0.0.20)
Requirement already satisfied: psycopg2-binary in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from timelink->-r requirements.txt (line 1)) (2.9.10)
Requirement already satisfied: py-markdown-table in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from timelink->-r requirements.txt (line 1)) (1.3.0)
Requirement already satisfied: python-jose[cryptography] in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from timelink->-r requirements.txt (line 1)) (3.4.0)
Requirement already satisfied: pandas in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from timelink->-r requirements.txt (line 1)) (2.2.3)
Requirement already satisfied: docker in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from timelink->-r requirements.txt (line 1)) (7.1.0)
Requirement already satisfied: jsonrpcclient in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from timelink->-r requirements.txt (line 1)) (4.0.3)
Requirement already satisfied: ipython in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from timelink->-r requirements.txt (line 1)) (9.1.0)
Requirement already satisfied: uvicorn in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from timelink->-r requirements.txt (line 1)) (0.34.1)
Requirement already satisfied: et-xmlfile in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from openpyxl->-r requirements.txt (line 2)) (2.0.0)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from jinja2->-r requirements.txt (line 3)) (3.0.2)
Requirement already satisfied: contourpy>=1.0.1 in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from matplotlib->-r requirements.txt (line 4)) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from matplotlib->-r requirements.txt (line 4)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from matplotlib->-r requirements.txt (line 4)) (4.57.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from matplotlib->-r requirements.txt (line 4)) (1.4.8)
Requirement already satisfied: numpy>=1.23 in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from matplotlib->-r requirements.txt (line 4)) (2.2.4)
Requirement already satisfied: packaging>=20.0 in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from matplotlib->-r requirements.txt (line 4)) (24.2)
Requirement already satisfied: pillow>=8 in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from matplotlib->-r requirements.txt (line 4)) (11.2.1)
Requirement already satisfied: pyparsing>=2.3.1 in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from matplotlib->-r requirements.txt (line 4)) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from matplotlib->-r requirements.txt (line 4)) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from python-dateutil>=2.7->matplotlib->-r requirements.txt (line 4)) (1.17.0)
Requirement already satisfied: Mako in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from alembic->timelink->-r requirements.txt (line 1)) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from alembic->timelink->-r requirements.txt (line 1)) (4.13.2)
Requirement already satisfied: requests>=2.26.0 in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from docker->timelink->-r requirements.txt (line 1)) (2.32.3)
Requirement already satisfied: urllib3>=1.26.0 in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from docker->timelink->-r requirements.txt (line 1)) (2.4.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from requests>=2.26.0->docker->timelink->-r requirements.txt (line 1)) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from requests>=2.26.0->docker->timelink->-r requirements.txt (line 1)) (3.10)
Requirement already satisfied: certifi>=2017.4.17 in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from requests>=2.26.0->docker->timelink->-r requirements.txt (line 1)) (2025.1.31)
Requirement already satisfied: starlette<0.47.0,>=0.40.0 in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from fastapi->timelink->-r requirements.txt (line 1)) (0.46.2)
Requirement already satisfied: annotated-types>=0.6.0 in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from pydantic->timelink->-r requirements.txt (line 1)) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.1 in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from pydantic->timelink->-r requirements.txt (line 1)) (2.33.1)
Requirement already satisfied: typing-inspection>=0.4.0 in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from pydantic->timelink->-r requirements.txt (line 1)) (0.4.0)
Requirement already satisfied: anyio<5,>=3.6.2 in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from starlette<0.47.0,>=0.40.0->fastapi->timelink->-r requirements.txt (line 1)) (4.9.0)
Requirement already satisfied: sniffio>=1.1 in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from anyio<5,>=3.6.2->starlette<0.47.0,>=0.40.0->fastapi->timelink->-r requirements.txt (line 1)) (1.3.1)
Requirement already satisfied: decorator in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from ipython->timelink->-r requirements.txt (line 1)) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from ipython->timelink->-r requirements.txt (line 1)) (1.1.1)
Requirement already satisfied: jedi>=0.16 in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from ipython->timelink->-r requirements.txt (line 1)) (0.19.2)
Requirement already satisfied: matplotlib-inline in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from ipython->timelink->-r requirements.txt (line 1)) (0.1.7)
Requirement already satisfied: pexpect>4.3 in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from ipython->timelink->-r requirements.txt (line 1)) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from ipython->timelink->-r requirements.txt (line 1)) (3.0.50)
Requirement already satisfied: pygments>=2.4.0 in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from ipython->timelink->-r requirements.txt (line 1)) (2.19.1)
Requirement already satisfied: stack_data in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from ipython->timelink->-r requirements.txt (line 1)) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from ipython->timelink->-r requirements.txt (line 1)) (5.14.3)
Requirement already satisfied: wcwidth in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython->timelink->-r requirements.txt (line 1)) (0.2.13)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from jedi>=0.16->ipython->timelink->-r requirements.txt (line 1)) (0.8.4)
Requirement already satisfied: ptyprocess>=0.5 in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from pexpect>4.3->ipython->timelink->-r requirements.txt (line 1)) (0.7.0)
Requirement already satisfied: pytz>=2020.1 in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from pandas->timelink->-r requirements.txt (line 1)) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from pandas->timelink->-r requirements.txt (line 1)) (2025.2)
Requirement already satisfied: ecdsa!=0.15 in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from python-jose[cryptography]->timelink->-r requirements.txt (line 1)) (0.19.1)
Requirement already satisfied: rsa!=4.1.1,!=4.4,<5.0,>=4.0 in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from python-jose[cryptography]->timelink->-r requirements.txt (line 1)) (4.9)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.1 in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from python-jose[cryptography]->timelink->-r requirements.txt (line 1)) (0.4.8)
Requirement already satisfied: cryptography>=3.4.0 in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from python-jose[cryptography]->timelink->-r requirements.txt (line 1)) (44.0.2)
Requirement already satisfied: cffi>=1.12 in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from cryptography>=3.4.0->python-jose[cryptography]->timelink->-r requirements.txt (line 1)) (1.17.1)
Requirement already satisfied: pycparser in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from cffi>=1.12->cryptography>=3.4.0->python-jose[cryptography]->timelink->-r requirements.txt (line 1)) (2.22)
Requirement already satisfied: executing>=1.2.0 in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from stack_data->ipython->timelink->-r requirements.txt (line 1)) (2.2.0)
Requirement already satisfied: asttokens>=2.1.0 in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from stack_data->ipython->timelink->-r requirements.txt (line 1)) (3.0.0)
Requirement already satisfied: pure-eval in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from stack_data->ipython->timelink->-r requirements.txt (line 1)) (0.2.3)
Requirement already satisfied: click>=8.0.0 in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from typer->timelink->-r requirements.txt (line 1)) (8.1.8)
Requirement already satisfied: shellingham>=1.3.0 in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from typer->timelink->-r requirements.txt (line 1)) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from typer->timelink->-r requirements.txt (line 1)) (14.0.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from rich>=10.11.0->typer->timelink->-r requirements.txt (line 1)) (3.0.0)
Requirement already satisfied: mdurl~=0.1 in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer->timelink->-r requirements.txt (line 1)) (0.1.2)
Requirement already satisfied: h11>=0.8 in /Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages (from uvicorn->timelink->-r requirements.txt (line 1)) (0.14.0)

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: pip install --upgrade pip

In [4]:
# NBVAL_IGNORE_OUTPUT
from timelink.notebooks import TimelinkNotebook
import os

tlnb = TimelinkNotebook()
tlnb.print_info()

WARNING:root:Reusing existing container great_greider

Timelink version: 1.1.26
Project name: dehergne-repertoire
Project home: /Users/jrc/develop/dehergne-repertoire
Database type: sqlite
Database name: dehergne_repertoire
Kleio image: timelinkserver/kleio-server
Kleio server token: KAOI9...
Kleio server URL: http://127.0.0.1:8088
Kleio server home: /Users/jrc/develop/dehergne-repertoire
Kleio server container: great_greider
Kleio version requested: latest
Kleio server version: 12.9.588 (2025-06-06 16:04:22)
SQLite directory: /Users/jrc/develop/dehergne-repertoire/database/sqlite
Database version: 6ccf1ef385a6
Call print_info(show_token=True) to show the Kleio Server token
Call print_info(show_password=True) to show the Postgres password
TimelinkNotebook(project_name=dehergne-repertoire, project_home=/Users/jrc/develop/dehergne-repertoire, db_type=sqlite, db_name=dehergne_repertoire, kleio_image=timelinkserver/kleio-server, kleio_version=latest, postgres_image=postgres, postgres_version=latest)

TimelinkNotebook created a database to store data and a Kleio server to 
translate transcriptions in Kleio notation into data that can be imported
into a database.

To get information about the database and the Kleio server do ```tnlb.print_info()```

### Database status

Count the number of rows in each table in the database.

In [5]:
# NBVAL_IGNORE_OUTPUT

tlnb.table_row_count_df()

               table  count
0               acts     28
1    alembic_version      1
2         aregisters      0
3         attributes  26819
4             blinks     98
5   class_attributes     58
6            classes     10
7           entities  32957
8        geoentities    359
9         kleiofiles     29
10             links     99
11           objects      0
12           persons   2132
13         relations   3534
14         rentities     46
15           sources     29
16            syslog      0
17            syspar      0

### Show the kleio files available

In [6]:
# NBVAL_IGNORE_OUTPUT

kleio_files = tlnb.get_kleio_files(match_path = True)
kleio_files

,path,name,modified,status,translated,errors,warnings,import_status,import_errors,import_warnings,import_error_rpt,import_warning_rpt,imported,rpt_url,xml_url
0,sources/dehergne-0-abrev.cli,dehergne-0-abrev.cli,2025-04-14 05:11:06.124864+00:00,V,2025-04-14 05:11:00+00:00,0,0,I,0,0,No errors,No warnings,2025-04-14 05:11:37.299110,/rest/reports/sources/dehergne-0-abrev.rpt,/rest/exports/sources/dehergne-0-abrev.xml
1,sources/dehergne-a.cli,dehergne-a.cli,2025-06-12 10:16:11.322832+00:00,T,2025-06-06 03:55:00+00:00,0,0,I,0,0,No errors,No warnings,2025-06-09 04:42:32.910620,/rest/reports/sources/dehergne-a.rpt,/rest/exports/sources/dehergne-a.xml
2,sources/dehergne-b.cli,dehergne-b.cli,2025-08-15 03:02:17.049776+00:00,T,2025-06-04 00:13:00+00:00,0,0,I,0,0,No errors,No warnings,2025-06-09 04:42:39.304542,/rest/reports/sources/dehergne-b.rpt,/rest/exports/sources/dehergne-b.xml
3,sources/dehergne-c.cli,dehergne-c.cli,2025-06-09 04:54:52.271057+00:00,V,2025-05-29 14:02:00+00:00,0,0,I,0,0,No errors,No warnings,2025-06-09 04:42:48.513367,/rest/reports/sources/dehergne-c.rpt,/rest/exports/sources/dehergne-c.xml
4,sources/dehergne-d.cli,dehergne-d.cli,2025-06-09 04:54:52.275558+00:00,V,2025-06-05 03:03:00+00:00,0,0,I,0,0,No errors,No warnings,2025-06-09 04:42:52.745787,/rest/reports/sources/dehergne-d.rpt,/rest/exports/sources/dehergne-d.xml
5,sources/dehergne-e.cli,dehergne-e.cli,2025-06-09 04:54:52.277401+00:00,V,2025-05-28 08:26:00+00:00,0,0,I,0,0,No errors,No warnings,2025-06-09 04:42:54.133535,/rest/reports/sources/dehergne-e.rpt,/rest/exports/sources/dehergne-e.xml
6,sources/dehergne-f.cli,dehergne-f.cli,2025-06-09 04:54:52.278048+00:00,V,2025-06-05 03:03:00+00:00,0,0,I,0,0,No errors,No warnings,2025-06-09 04:43:00.181349,/rest/reports/sources/dehergne-f.rpt,/rest/exports/sources/dehergne-f.xml
7,sources/dehergne-g.cli,dehergne-g.cli,2025-06-09 04:54:52.281060+00:00,V,2025-06-04 00:17:00+00:00,0,0,I,0,0,No errors,No warnings,2025-06-09 04:43:06.803211,/rest/reports/sources/dehergne-g.rpt,/rest/exports/sources/dehergne-g.xml
8,sources/dehergne-h.cli,dehergne-h.cli,2025-06-09 04:54:52.283525+00:00,V,2025-05-28 07:32:00+00:00,0,0,I,0,0,No errors,No warnings,2025-06-09 04:43:09.234806,/rest/reports/sources/dehergne-h.rpt,/rest/exports/sources/dehergne-h.xml
9,sources/dehergne-i.cli,dehergne-i.cli,2025-06-09 04:54:52.284346+00:00,V,2025-06-03 14:25:00+00:00,0,0,I,0,0,No errors,No warnings,2025-06-09 04:43:10.745085,/rest/reports/sources/dehergne-i.rpt,/rest/exports/sources/dehergne-i.xml
10,sources/dehergne-j.cli,dehergne-j.cli,2025-06-09 04:54:52.284889+00:00,V,2025-05-28 08:26:00+00:00,0,0,I,0,0,No errors,No warnings,2025-06-09 04:43:13.074371,/rest/reports/sources/dehergne-j.rpt,/rest/exports/sources/dehergne-j.xml
11,sources/dehergne-k.cli,dehergne-k.cli,2025-06-09 04:54:52.285703+00:00,V,2025-06-03 14:28:00+00:00,0,0,I,0,0,No errors,No warnings,2025-06-09 04:43:15.723110,/rest/reports/sources/dehergne-k.rpt,/rest/exports/sources/dehergne-k.xml
12,sources/dehergne-l.cli,dehergne-l.cli,2025-08-15 03:44:52.177050+00:00,T,2025-06-05 03:03:00+00:00,0,0,I,0,0,No errors,No warnings,2025-06-09 04:43:22.454435,/rest/reports/sources/dehergne-l.rpt,/rest/exports/sources/dehergne-l.xml
13,sources/dehergne-locations-1644.cli,dehergne-locations-1644.cli,2025-06-09 04:54:52.289953+00:00,V,2025-06-06 02:43:00+00:00,0,0,I,0,0,No errors,No warnings,2025-06-09 04:43:25.590499,/rest/reports/sources/dehergne-locations-1644.rpt,/rest/exports/sources/dehergne-locations-1644.xml
14,sources/dehergne-locations-1701.cli,dehergne-locations-1701.cli,2025-06-09 04:54:52.291489+00:00,V,2025-06-05 03:13:00+00:00,0,0,I,0,0,No errors,No warnings,2025-06-09 04:43:28.167601,/rest/reports/sources/dehergne-locations-1701.rpt,/rest/exports/sources/dehergne-locations-1701.xml
15,sources/dehergne-m.cli,dehergne-m.cli,2025-06-09 04:54:52.292952+00:00,V,2025-06-03 14:25:00+00:00,0,0,I,0,0,No errors,No warnings,2025-06-09 04:43:35.975599,/rest/reports/sources/dehergne-m.rpt,/rest/exports/sources/dehergne-m.xml
16,sources/dehergne-n.cli,dehergne-n.cli,2025-04-14 05:11:22.734506+00:00,V,2025-04-14 05:11:00+00:00,0,0,I,0,0,No errors,No warnings,2025-04-14 05:12:30.418032,/rest/reports/sources/dehergne-n.rpt,/rest/exports/sources/dehergne-n.xml
17,sources/dehergne-o.cli,dehergne-o.cli,2025-06-09 04:54:52.297238+00:00,V,2025-06-04 00:22:00+00:00,0,0,I,0,0,No errors,No warnings,2025-06-09 04:43:37.571776,/rest/reports/sources/dehergne-o.rpt,/rest/exports/sources/dehergne-o.xml
18,sources/dehergne-p.cli,dehergne-p.cli,2025-06-09 04:54:52.297937+00:00,V,2025-06-05 03:03:00+00:00,0,0,I,0,0,No errors,No warnings,2025-06-09 04:43:44.220866,/rest/reports/sources/dehergne-p.rpt,/rest/exports/sources/dehergne-p.xml
19,sources/dehergne-q.cli,dehergne-q.cli,2025-04-14 05:11:24.903064+00:00,V,2025-04-14 05:11:00+00:00,0,0,I,0,0,No errors,No warnings,2025-04-14 05:12:38.476645,/rest/reports/sources/dehergne-q.rpt,/rest/exports/sources/dehergne-q.xml
20,sources/dehergne-r.cli,dehergne-r.cli,2025-06-12 10:16:11.323303+00:00,T,2025-05-28 23:22:00+00:00,0,0,I,0,0,No errors,No warnings,2025-06-09 04:43:51.295304,/rest/reports/sources/dehergne-r.rpt,/rest/exports/sources/dehergne-r.xml
21,sources/dehergne-s.cli,dehergne-s.cli,2025-06-09 04:54:52.304647+00:00,V,2025-05-28 09:27:00+00:00,0,0,I,0,0,No errors,No warnings,2025-06-09 04:43:59.107317,/rest/reports/sources/dehergne-s.rpt,/rest/exports/sources/dehergne-s.xml
22,sources/dehergne-t.cli,dehergne-t.cli,2025-06-09 04:54:52.307814+00:00,V,2025-05-28 11:51:00+00:00,0,0,I,0,0,No errors,No warnings,2025-06-09 04:44:03.627749,/rest/reports/sources/dehergne-t.rpt,/rest/exports/sources/dehergne-t.xml
23,sources/dehergne-u.cli,dehergne-u.cli,2025-04-14 05:11:31.500511+00:00,V,2025-04-14 05:11:00+00:00,0,0,I,0,0,No errors,No warnings,2025-04-14 05:12:54.779184,/rest/reports/sources/dehergne-u.rpt,/rest/exports/sources/dehergne-u.xml
24,sources/dehergne-v.cli,dehergne-v.cli,2025-06-09 04:54:52.309741+00:00,V,2025-05-28 08:05:00+00:00,0,0,I,0,0,No errors,No warnings,2025-06-09 04:44:09.658966,/rest/reports/sources/dehergne-v.rpt,/rest/exports/sources/dehergne-v.xml
25,sources/dehergne-w.cli,dehergne-w.cli,2025-06-09 04:54:52.311802+00:00,V,2025-05-28 08:26:00+00:00,0,0,I,0,0,No errors,No warnings,2025-06-09 04:44:11.169602,/rest/reports/sources/dehergne-w.rpt,/rest/exports/sources/dehergne-w.xml
26,sources/dehergne-x.cli,dehergne-x.cli,2025-06-09 04:54:52.312263+00:00,V,2025-06-03 14:25:00+00:00,0,0,I,0,0,No errors,No warnings,2025-06-09 04:44:12.995343,/rest/reports/sources/dehergne-x.rpt,/rest/exports/sources/dehergne-x.xml
27,sources/dehergne-y.cli,dehergne-y.cli,2025-06-09 04:54:52.312894+00:00,V,2025-05-28 08:31:00+00:00,0,0,I,0,0,No errors,No warnings,2025-06-09 04:44:14.410675,/rest/reports/sources/dehergne-y.rpt,/rest/exports/sources/dehergne-y.xml
28,sources/dehergne-z.cli,dehergne-z.cli,2025-04-14 05:11:35.345099+00:00,V,2025-04-14 05:11:00+00:00,0,0,I,0,0,No errors,No warnings,2025-04-14 05:38:12.989318,/rest/reports/sources/dehergne-z.rpt,/rest/exports/sources/dehergne-z.xml

## Optionally clean translations

In [7]:
# NBVAL_IGNORE_OUTPUT
# 
# tlnb.kleio_server.translation_clean("", recurse="yes")


# Update the database from Kleio sources.

Updates source translations and imports into database sources with no errors.

Only changed files since last import, or new files, will be processed.

In [17]:
# NBVAL_IGNORE_OUTPUT

import logging
logging.basicConfig(level=logging.DEBUG)
path =  ''
tlnb.update_from_sources(path=path, match_path = True, with_import_errors=True)
# get the import status
import_status = tlnb.get_import_status(match_path = True)
# list those with import_error > 0 or error > 0
errors = import_status.query("import_errors > 0 or errors > 0")
errors[['name', 'import_errors', 'errors']]

/Users/jrc/develop/dehergne-repertoire/.venv/lib/python3.13/site-packages/timelink/api/models/pom_som_mapper.py:698: UserWarning: Ambiguous mapping! more than one element of rel is mapped to column class date check mapping for this group
  element: KElement = group.get_element_by_name_or_class(cattr.colclass)

Empty DataFrame
Columns: [name, import_errors, errors]
Index: []

## Check the status of the files

Check the import status of the translated files

* I: Imported
* E: Imported with error
* W: Imported with warnings no errors
* N: Not imported
* U: Translation updated need to reimport

In [12]:
# NBVAL_IGNORE_OUTPUT

imported_files_df = tlnb.get_import_status(match_path=True)
imported_files_df[["import_status","import_errors","import_warnings","name","errors","warnings","path"]].sort_values("name")

,import_status,import_errors,import_warnings,name,errors,warnings,path
0,I,0,0,dehergne-0-abrev.cli,0,0,sources/dehergne-0-abrev.cli
1,I,0,0,dehergne-a.cli,0,0,sources/dehergne-a.cli
2,I,0,0,dehergne-b.cli,0,0,sources/dehergne-b.cli
3,I,0,0,dehergne-c.cli,0,0,sources/dehergne-c.cli
4,I,0,0,dehergne-d.cli,0,0,sources/dehergne-d.cli
5,I,0,0,dehergne-e.cli,0,0,sources/dehergne-e.cli
6,I,0,0,dehergne-f.cli,0,0,sources/dehergne-f.cli
7,I,0,0,dehergne-g.cli,0,0,sources/dehergne-g.cli
8,I,0,0,dehergne-h.cli,0,0,sources/dehergne-h.cli
9,I,0,0,dehergne-i.cli,0,0,sources/dehergne-i.cli
10,I,0,0,dehergne-j.cli,0,0,sources/dehergne-j.cli
11,I,0,0,dehergne-k.cli,0,0,sources/dehergne-k.cli
12,I,0,0,dehergne-l.cli,0,0,sources/dehergne-l.cli
13,I,0,0,dehergne-locations-1644.cli,0,0,sources/dehergne-locations-1644.cli
14,I,0,0,dehergne-locations-1701.cli,0,0,sources/dehergne-locations-1701.cli
15,I,0,0,dehergne-m.cli,0,0,sources/dehergne-m.cli
16,I,0,0,dehergne-n.cli,0,0,sources/dehergne-n.cli
17,I,0,0,dehergne-o.cli,0,0,sources/dehergne-o.cli
18,I,0,0,dehergne-p.cli,0,0,sources/dehergne-p.cli
19,I,0,0,dehergne-q.cli,0,0,sources/dehergne-q.cli
20,I,0,0,dehergne-r.cli,0,0,sources/dehergne-r.cli
21,I,0,0,dehergne-s.cli,0,0,sources/dehergne-s.cli
22,I,0,0,dehergne-t.cli,0,0,sources/dehergne-t.cli
23,I,0,0,dehergne-u.cli,0,0,sources/dehergne-u.cli
24,I,0,0,dehergne-v.cli,0,0,sources/dehergne-v.cli
25,I,0,0,dehergne-w.cli,0,0,sources/dehergne-w.cli
26,I,0,0,dehergne-x.cli,0,0,sources/dehergne-x.cli
27,I,0,0,dehergne-y.cli,0,0,sources/dehergne-y.cli
28,I,0,0,dehergne-z.cli,0,0,sources/dehergne-z.cli

### Files with translation errors

In [13]:
# NBVAL_IGNORE_OUTPUT

errors = imported_files_df[imported_files_df.errors>0][["status", "errors","import_warnings","name","imported","warnings","path"]].sort_values("name")
errors

Empty DataFrame
Columns: [status, errors, import_warnings, name, imported, warnings, path]
Index: []

### Check a translation report

If needed to check for errors.

In [14]:
# NBVAL_IGNORE_OUTPUT

file_number=list(errors.index.unique())
if len(file_number) > 0:
    rpt = tlnb.get_translation_report(imported_files_df, file_number)
    print(rpt)
else:
    print("No errors found")

No errors found

### Files with import errors

In case there are errors in the import phase check the import report.

In [15]:
# NBVAL_IGNORE_OUTPUT

ierrors = imported_files_df[imported_files_df.import_errors>0][["import_status", "import_errors","import_warnings","name","imported","errors","warnings","path"]].sort_values("name")
list(ierrors.index)

[]

In [16]:
# NBVAL_IGNORE_OUTPUT

rpt = tlnb.get_import_rpt(imported_files_df, rows=list(ierrors.index))
print(rpt)