# Places

Analysis of places in the individual biographies.

This notebook collects all the places mentioned in the individual biographies and uses wikidata to extract associated information about them, namely current names, coordinates, and adminstrative information (present day).

Relevant to this notebook is the list of attribute types that receive place names as values.

The list is the following:

- 'nascimento'
- 'jesuita-entrada'
- 'partida'
- 'chegada'
- 'estadia'
- 'estadia-x'
- 'jesuita-votos-local'
- 'jesuita-ordenacao-padre'
- 'morte'

Files generated by this notebook:
- "../inferences/locations_names.xlsx" persons id and name, place of stay, attribute type, wikidata, date...
- "../inferences/locations_names_places_dates_only.xlsx" without wikidata
- "../inferences/locations_names_no_wikidata.xlsx" places with no wikidata
- "inferences/wikidata-references/locations_names_wikidata.csv"

In [4]:
from timelink.notebooks import TimelinkNotebook

tlnb = TimelinkNotebook()
tlnb.print_info()

WARNING:root:Reusing existing container great_greider

Timelink version: 1.1.26
Project name: dehergne-repertoire
Project home: /Users/jrc/develop/dehergne-repertoire
Database type: sqlite
Database name: dehergne_repertoire
Kleio image: timelinkserver/kleio-server
Kleio server token: KAOI9...
Kleio server URL: http://127.0.0.1:8088
Kleio server home: /Users/jrc/develop/dehergne-repertoire
Kleio server container: great_greider
Kleio version requested: latest
Kleio server version: 12.9.588 (2025-06-06 16:04:22)
SQLite directory: /Users/jrc/develop/dehergne-repertoire/database/sqlite
Database version: 6ccf1ef385a6
Call print_info(show_token=True) to show the Kleio Server token
Call print_info(show_password=True) to show the Postgres password
TimelinkNotebook(project_name=dehergne-repertoire, project_home=/Users/jrc/develop/dehergne-repertoire, db_type=sqlite, db_name=dehergne_repertoire, kleio_image=timelinkserver/kleio-server, kleio_version=latest, postgres_image=postgres, postgres_version=latest)

Define attributes types that have locations as values.

In [7]:
attributes_with_place_names = [
    'nascimento',
    'jesuita-entrada',
    'partida',
    'chegada',
    'estadia',
    'estadia-x',
    'jesuita-votos-local',
    'jesuita-ordenacao-padre',
    'morte'
]

attributes_with_wikidata = [f"{attr}@wikidata" for attr in attributes_with_place_names]
attributes_with_wikidata

['nascimento@wikidata',
 'jesuita-entrada@wikidata',
 'partida@wikidata',
 'chegada@wikidata',
 'estadia@wikidata',
 'estadia-x@wikidata',
 'jesuita-votos-local@wikidata',
 'jesuita-ordenacao-padre@wikidata',
 'morte@wikidata']

Collect all the individuals with attributes related to locations. Make note of the dates of the attributes and infer dates when missing, based on last known date for a previous location attribute. Extract wikidata ids for the locations if available.

In [14]:
import pandas as pd
from timelink.pandas import entities_with_attribute
from timelink.kleio.utilities import format_timelink_date
from dehergne_util import get_linked_entity_id

# show 500 rows
pd.set_option('display.max_rows', 1550)

places_of_stay = entities_with_attribute(
    entity_type='person',
    show_elements=['name','groupname','the_line','the_order','extra_info'],
    the_type=attributes_with_place_names,
    column_name='place',
    db=tlnb.db,
)

# fillna with "?"
places_of_stay['place'] = places_of_stay['place'].fillna('?')

# remove rows where place == '?'
places_of_stay = places_of_stay[places_of_stay['place'] != '?']

# this sequence replaces missing dates with the value of the previous date
# followed by ">". This allows to use the information that although the date
# is unkown it has happened after a certain date
# we need the id in a column to group by it (it is currently in the index)
# TODO: maybe an option in entities_with_attribute and compute intervals using
#       post quem and ante quem dates. See https://github.com/time-link/timelink-kleio/issues/1

places_of_stay['id_col'] = places_of_stay.index

# We try to infer the date of stay from the previous date known
# create a copy of the date column to replace the '0' values with NaN
places_of_stay['place.date_inferred'] = places_of_stay['place.date'].replace('0', pd.NA)

# order by id and line to have the missing date values filled with the previous date
places_of_stay = places_of_stay.sort_values(by=['id_col', 'place.line'])
# use ffill to fill the missing values with the previous value
places_of_stay['place.date_inferred'] = places_of_stay.groupby(['id_col'])['place.date_inferred'].ffill()
# create a column to flag the inferred dates
places_of_stay['place.date_is_inferred'] = places_of_stay['place.date_inferred'] != places_of_stay['place.date']
# reset index
places_of_stay.reset_index(inplace=True)
# if data_is_inferred set date_inferred to date_inferrred+">"
places_of_stay.loc[places_of_stay['place.date_is_inferred'], 'place.date_inferred'] = places_of_stay['place.date_inferred'] + '>'
# set missing value to ''
places_of_stay['place.date_inferred'] = places_of_stay['place.date_inferred'].fillna('')
# restore index
places_of_stay.index = places_of_stay['id_col']

# create a new column named "wikidata_id" with the wikidata id extracted from place.comment
places_of_stay['wikidata_id'] = places_of_stay['place.comment'].apply(get_linked_entity_id, linked_data_provider='wikidata', if_missing='no wikidata')
# create a new column with the formatted date
places_of_stay['place.date_inferred.formatted'] = places_of_stay['place.date_inferred'].apply(format_timelink_date)

# places_of_stay.info()
# show results
show_only=10
cols=['place','place.type','place.attr_id','wikidata_id','place.date_inferred','place.date_inferred.formatted','groupname','name','place.comment','place.original','place.date_is_inferred','place.line','place.extra_info']
places_of_stay[places_of_stay.groupname=='n'][cols].sort_values(by=['place','place.date_inferred']).head(show_only)

,place,place.type,place.attr_id,wikidata_id,place.date_inferred,place.date_inferred.formatted,groupname,name,place.comment,place.original,place.date_is_inferred,place.line,place.extra_info
id_col,,,,,,,,,,,,,
deh-johannes-ciermans,"'s-Hertogenbosch, Holanda",nascimento,deh-johannes-ciermans-att1059-277,Q2766547,16020407,1602-04-07,n,Johannes Ciermans,@wikidata:Q2766547,Bois-le-duc,False,1507,"{'id': {'kleio_element_name': 'id', 'kleio_ele..."
deh-charles-francois-xavier-de-brevedent,Abissínia,partida,deh-charles-francois-xavier-de-brevedent-att10...,Q207521,16980610,1698-06-10,n,Charles-François Xavier de Brévedent,@wikidata:Q207521,None,False,1358,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-estevao-coelho,"Abrantes, diocese da Guarda",nascimento,deh-estevao-coelho-att1198-277,Q331191,1586,1586,n,Estêvão Coelho,@wikidata:Q331191,Abrantès de Guarda?,False,1678,"{'id': {'kleio_element_name': 'id', 'kleio_ele..."
deh-antonio-sedeno,"Acapulco, México",estadia,deh-antonio-sedeno-att429-192,Q81398,15810329,1581-03-29,n,Antonio Sedeño,@wikidata:Q81398,None,False,687,"{'id': {'kleio_element_name': 'id', 'kleio_ele..."
deh-antoine-rene-de-brasle,"Acapulco, México",estadia,deh-antoine-rene-de-brasle-att990-233,Q81398,<1707,<1707,n,Antoine-René de Brasle,a caminho de Manila @wikidata:Q81398,None,False,1297,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-antonio-de-magalhaes,Afeganistão,estadia,deh-antonio-de-magalhaes-att93-238,Q889,17000000,1700,n,António de Magalhães,@wikidata:Q889,None,False,145,"{'id': {'kleio_element_name': 'id', 'kleio_ele..."
deh-pierre-albier,Agen,jesuita-votos-local,deh-pierre-albier-att214-253,Q6625,16540712,1654-07-12,n,Pierre Albier,@wikidata:Q6625,None,False,294,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-philippe-avril,Agen,estadia,deh-philippe-avril-att1017-253,Q6625,16910000,1691,n,Philippe Avril,@wikidata:Q6625,None,False,1442,"{'the_value': {'kleio_element_name': 'valor', ..."
deh-bento-de-gois,Agra,estadia,deh-bento-de-gois-att464-180,Q42941,16021029,1602-10-29,n,Bento de Góis,@wikidata:Q42941,None,False,614,"{'id': {'kleio_element_name': 'id', 'kleio_ele..."
deh-antonio-de-andrade,Agra,estadia,deh-antonio-de-andrade-att729-253,Q42941,16240330,1624-03-30,n,António de Andrade,@wikidata:Q42941,None,False,1063,"{'the_value': {'kleio_element_name': 'valor', ..."

### Save to Excel

In [ ]:
filename = "../inferences/locations_names.xlsx"
places_of_stay[cols].sort_values(by=['place','place.date_inferred']).to_excel(filename, sheet_name='wikidata', index=True)
# another version without wikidata_id for unbiased LLM reasoning
filename = "../inferences/locations_names_places_dates_only.xlsx"
places_of_stay[['place','place.date_inferred.formatted', 'name','place.type','place.original']].sort_values(by=['place','place.date_inferred.formatted']).to_excel(filename, sheet_name='wikidata', index=True)

### Locations with no wikidata id

In [29]:
places_of_stay[
    (places_of_stay['wikidata_id'] == 'no wikidata') &
    (~places_of_stay['place'].str.startswith('['))
][cols].sort_values(by=['place', 'place.date_inferred'])

,place,name,place.type,place.date_inferred,place.obs
id_col,,,,,
deh-jose-de-lima-ref2,Aguiar,José de Lima,nascimento,17391115,
deh-miguel-vieira,Aquilon,Miguel Vieira,estadia,,
deh-simao-da-silveira,Aquilon,Simão da Silveira,estadia,,
deh-manuel-jose-ref2,Ascitano,Emmanuel Josephus,morte,17650000,
deh-claude-francois-loppin,Bellegarde,Claude-François Loppin,nascimento,17070913,
deh-joaquim-lobo,"Cadaval, diocese de Coimbra",Joaquim Lobo,nascimento,17320224,
deh-antonio-de-gouvea,"Casal, diocese de Viseu",António de Gouveia,nascimento,1592,""""""" segundo Gouvea, A. de, & Araújo, H. P. de...."
deh-gaspar-ferreira,"Castrofornos, diocese de Viseu",Gaspar Ferreira,nascimento,1571,
deh-mauro-de-azevedo,Celorico,Mauro de Azevedo,nascimento,16470000,
deh-diogo-vidal,"Cerradas, diocese de Lisboa",Diogo Vidal,nascimento,16600423,
deh-mathurin-lamathe,"Chang-tsin do Yüansi, Hou-pei",Mathurin Lamathe,morte,17861203,
deh-simon-xavier-a-cunha-wou-li,"Changshu, Tch'ang-chou, Kiangnan",Simon-Xavier a Cunha Wou Li,nascimento,16320801,
deh-mathurin-lamathe,"Chayüankow, Hukwang",Mathurin Lamathe,jesuita-votos-local,17590401,
deh-pero-rodrigues,China,Pero Rodrigues,nascimento,1568,
deh-pierre-tchen,Choui tcheou San Kia (capela da Beata Virgem M...,Pierre T'chen,jesuita-votos-local,17450908,recebe votos das mãos do P. Louis-Joseph Lefeb...
deh-antonio-da-silva-ref3,"Comba, diocese de Coimbra",António da Silva,nascimento,1637,
deh-inacio-francisco,"Conraria, diocese de Coimbra",Inácio Francisco,nascimento,17250814,
deh-antonio-de-magalhaes,"Cortiços, diocese de Viseu",António de Magalhães,nascimento,16770000,
deh-andre-da-costa,"Cuamani, província de Goa",André da Costa,morte,17220728,
deh-magnani-ref1,Czerczerse,Agostino Magnani,morte,17940421,
deh-johann-terrenz-schreck,Diocese de Constance (parte da Suábia) no grão...,Johann Terrenz Schreck,nascimento,1576,
deh-jose-mendes-dos-reis-ref2,Diocese de Viso,Joachim Joseph,nascimento,17120906,
deh-manuel-marques,Diocese de Évora,Manuel Marques,nascimento,16740100,
deh-manuel-de-carvalho-ii-ref2,Diocese de Évora,Manuel de Carvalho,nascimento,1710,
deh-johann-alberich,Dorenbüren,Johann Alberich,nascimento,15860500,
deh-manuel-jose,"Guemara, diocese de Braga",Manuel José,nascimento,17120826,
deh-jose-de-espinha,Hami,José de Espinha,jesuita-votos-local,17561128,
deh-diogo-vidal,"Hien, Tonquim",Diogo Vidal,jesuita-votos-local,16950224,
deh-manuel-rodrigues-ii-ref4,"Hirubale, Misore",Emanuel Rodriguez,jesuita-votos-local,16750815,
deh-dominique-lou-sseu-mei,"Hwating (Houa-t'ing), do Song-kiang fou, Kiangsu",Dominique Lou Sseu-Mei,nascimento,1630,
deh-jean-yao,Hweichow (Houei-tcheou fou) (bairro de Ché-hie...,Jean Yao,nascimento,17220000,
deh-jacques-cardoso,"Hweichow, Houei-tcheou fou, Anhwei, Kiang-nan",Jacques Cardoso,nascimento,17110312,
deh-francisco-da-veiga,Ilhas,Francisco da Veiga,nascimento,1631,
deh-gaspar-coelho,"Kasuza, Arima, Japão",Gaspar Coelho,morte,15900525,
deh-melchior-mora,"Katsusa, Japão",Melchior Mora,jesuita-votos-local,15910630,
deh-francesco-pasio,"Katsusa, Japão",Francesco Pasio,jesuita-votos-local,15910701,
deh-paul-banhes-wan,"Kienchang, Kien-tch'ang fou, Kiangsi",Paul Banhes Wan,nascimento,16310000,REVER
deh-dionisio-ferreira,"Ko-li-tsem do Kiating, Kiangnan",Dionísio Ferreira,estadia,1745,
deh-dionisio-ferreira,"Ko-li-tsem do Kiating, Kiangnan",Dionísio Ferreira,estadia,17531208,
deh-paulo-de-campos,"Ké Diet, Tonquim",Paulo de Campos,jesuita-votos-local,17540815,
deh-sebastiao-de-almeida,Lagéas,Sebastião de Almeida,nascimento,16220000,
deh-domingos-alvares,"Lanhoso, diocese de Braga",Domingos Álvares,nascimento,16510000,
deh-nicolas-marie-roy,"Lao chan oua, Hou-kouang",Nicolas-Marie Roy,jesuita-votos-local,17590815,
deh-joseph-saraiva-chen,Leou-kia-tchouang do Chou-lou hien,Joseph Saraiva Chen,jesuita-votos-local,17440607,
deh-jean-francois-foucquet,"Liankiang fou, Kiangsi",Jean-François Foucquet,estadia,1703,
deh-jean-francois-foucquet,Linkiang fou,Jean-François Foucquet,estadia,1709,
deh-jose-simoes,Lintsing,José Simões,estadia,17070600,
deh-jean-francois-beuth-ref1-pai,"Lixel, Saxe",Auguste Beyth,nascimento,000000,
deh-romain-hinderer,Lofeu,Romain Hinderer,estadia,17221228,
deh-romain-hinderer,Lofeu,Romain Hinderer,estadia,17230414,
deh-manuel-de-carvalho-ii-ref3,"Louredo, diocese de Coimbra",Manuel de Carvalho,nascimento,1737,
deh-manuel-de-pereira-ii,Lugar da Cruz,Manuel de Pereira,nascimento,16370000,
deh-manuel-de-carvalho,"Làngòi, Tonquim",Manuel de Carvalho,jesuita-votos-local,17411112,
deh-pedro-de-francisco-ref1,"Mala, Espanha",Pedro de Fernandes,nascimento,,
deh-nicolas-zarate,Maxagongdong,Nicolás Zárate,estadia,17250000,
deh-tome-vaz,Missão dos Rios de Cuama,Tomé Vaz,estadia,,
deh-baltasar-caldeira,Mogor,Baltasar Caldeira,estadia,,
deh-manuel-henriques,Montemor,Manuel Henriques,nascimento,16230000,
deh-juan-miguel-de-irigoyen,"Monzei, Filipinas",Juan Miguel de Irigoyen,morte,16991013,
deh-manuel-jose-de-carvalho,"Moreta, diocese de Coimbra",Manuel José de Carvalho,nascimento,17320805,
deh-pierre-amys,Moulins,Pierre Amys,jesuita-votos-local,16890202,
deh-manswet-skokowski,Mscislaviae,Manswet Skokowvski,morte,17980208,
deh-jose-de-sousa,"Múrcia, diocese de Braga",José de Sousa,nascimento,1696,
deh-vicent-caun,Nagasaki,Vincent Caun,morte,16260620,
deh-simao-rodrigues,"Nan cham, Kiangsi",Simão Rodrigues,jesuita-votos-local,16820202,
deh-etienne-joseph-le-couteulx,Nan tchang fou,Etienne-Joseph Le Couteulx,jesuita-votos-local,17020202,
deh-philipp-sibin,"Nehaus, Westphalia",Philipp Sibin,nascimento,16791211,
deh-jakob-graff,Niederberg,Jakob Graff,nascimento,17090813,
deh-pierre-quenein,Oriente,Pierre Quenein,estadia,16960000,
deh-francisco-de-oria,Ozukio (noviciado),Francisco de Oria,jesuita-entrada,15811100,
deh-louis-marie-dugad,"Pe-tsien-chan, China",Louis-Marie Dugad,jesuita-votos-local,17400815,
deh-felix-da-rocha,Petit Tibet «Kinchuen»,Félix da Rocha,estadia,1774,
deh-felix-da-rocha,Petit Tibet «Kinchuen»,Félix da Rocha,estadia,1777,
deh-leon-pascal-baron,"Petsiuenchan, Houkouang (Oratório)",Léon-Pascal Baron,jesuita-votos-local,17710815,
deh-manoel-soares,"Pouva, diocese de Portalegre",Manoel Soares,nascimento,1614,
deh-antonio-ferreira-ref2,Prisão,António Ferreira,morte,17610624,
deh-etienne-yang,"Pé-pou, Linkiang fou",Etienne Yang,estadia,17870500,
deh-joseph-louis-desrobert,"Pé-tsiuen-chan, Hukwang",Joseph-Louis Desrobert,estadia,,
deh-aleixo-rodrigues,"Quintas, diocese de Braga",Aleixo Rodrigues,nascimento,17260503,
deh-antonio-de-mursia,"Rasto, diocese de Braga",António de Mursia,nascimento,16700000,
deh-joao-pereira-ii,"Redondo, diocese de Évora",João Pereira,nascimento,16630524,
deh-joseph-henry-marie-de-premare,Residência francesa «Vuen ngan juxta murum qui...,Joseph Henry-Marie de Prémare,estadia,,
deh-martino-martini,Rina (casa professa),Martino Martini,jesuita-votos-local,16550815,
deh-joao-barradas,Rio Kan,João Barradas,morte,15940000,
deh-manuel-de-figueiredo,"S. André de Medi, diocese do Porto",Manuel de Figueiredo,nascimento,1591,
deh-joao-belchior-ribeiro,"S. Pedro de Tarrados, diocese de Braga",João Belchior Ribeiro,nascimento,1589,
deh-louis-joseph-le-febure,San kiao hou kia,Louis-Joseph Le Febure,jesuita-votos-local,17410319,
deh-inacio-de-sousa-ref2,"Senna, província de Goa",Inácio de Sousa,morte,,
deh-cyr-contancin,Shaohing,Cyr Contancin,jesuita-votos-local,17060114,
deh-pierre-kieou,"Shaohing (Chao-hing fou, Tchö-kiang)",Pierre K'ieou,nascimento,16860501,
deh-inacio-da-costa,Si-ngan,Inácio da Costa,jesuita-votos-local,16401104,
deh-joao-duarte,Sian tan hien,João Duarte,jesuita-votos-local,17060815,
deh-julien-gonzaga-tchang,Siangtang du Hukwang,Julien Gonzaga Tchang,estadia,1691,
deh-julien-gonzaga-tchang,Siangtang du Hukwang,Julien Gonzaga Tchang,estadia,1712,
deh-etienne-faber,"Siao-tchai de Han-tchong, Shensi",Etienne Faver,morte,16570510,
deh-johann-siebert,"Sinhoua, Hué",Johann Siebert,jesuita-votos-local,17410528,
deh-francisco-da-costa,"Sinoae, Cochinchina",Francisco da Costa,jesuita-votos-local,17240430,
deh-joseph-saraiva-chen,"Sou-kiang fou, Kiangnan",Joseph Saraiva Chen,nascimento,17091031,
deh-tome-da-silva,"Sousa, diocese de Coimbra",Tomé da Silva,nascimento,17300322,
deh-martino-martini,"Suian, Souei-ngan hien",Martino Martini,estadia,,
deh-martim-correa,Sum Kiam (casa de um cristão),Martim Correa,jesuita-votos-local,17320803,
deh-jean-fernandes-tchong,"Sunwui (Sin-houei hien), Kwangtung",Jean Fernandes Tchong,nascimento,1581,
deh-sebastien-fernandes-tchong,Sunwui (Sin-houei),Sébastien Fernandes Tchong,nascimento,1562,
deh-jean-etienne-kao,Süanhwa (Siuan-houa) fou,Jean-Etienne Kao,nascimento,17051130,
deh-jean-regis-lieou,"Süanhwa, Hopei",Jean-Régis-Lieou,nascimento,17171010,
deh-antonio-posateri,"T'ai-yüan fou, Chan-si",Antonio Posateri,morte,17050118,
deh-gottfried-xaver-von-laimbeckhoven,T'ang-kia-hiang,Gottfried Xaver von Laimbeckhoven,morte,17870522,
deh-manuel-camello,Tanna (colégio),Manuel Camello,jesuita-votos-local,17161213,
deh-pieter-thomas-van-hamme,"Tarahumaras, México",Pieter Thomas van Hamme,estadia,1684,
deh-pieter-thomas-van-hamme,"Tarahumaras, México",Pieter Thomas van Hamme,estadia,1689,
deh-maur-tsao,Tcha-yuen-keou,Maur Ts'ao,jesuita-votos-local,17590326,
deh-manuel-da-mata,Tchen-kiang,Manuel da Mata,jesuita-votos-local,17010220,
deh-jose-pereira,Tchen-kiang fou,José Pereira,jesuita-votos-local,17070327,
deh-francisco-pires-ref3,Terceira de Braga,Francisco Pires,nascimento,15450000,
deh-antonio-jose-henriques,Tongko (casa de Philippe Wang),António-José Henriques,estadia,17471221,
deh-aloys-moriz,Tonkosz,Aloys Moriz,morte,18050124,
deh-antonio-pais,Toreguia,António Pais,nascimento,15360000,
deh-manuel-da-motta,"U cham fu, Hou-kouang",Manuel da Motta,jesuita-votos-local,17671213,
deh-luis-de-caldas,"Valadares, diocese de Braga",Luís de Caldas,nascimento,16891120,
deh-verissimo-nunes,"Vamias, diocese de Viseu",Veríssimo Nunes,nascimento,17260506,
deh-joao-da-veiga,Verros,João da Veiga,nascimento,1597,
deh-joao-de-figueiredo,Viana,João de Figueiredo,nascimento,1631,
deh-simao-martins,"Vila Pouca do Campo, diocese de Coimbra",Simão Martins,nascimento,16190000,
deh-joao-da-fonseca-ii,"Villacova de Suevo, diocese de Coimbra",João da Fonseca,nascimento,17310912,
deh-ignace-hiu,"Wou-ho, Anhwei",Ignace Hiu,nascimento,16970000,
deh-gottfried-xaver-von-laimbeckhoven,Wouho,Gottfried Xaver von Laimbeckhoven,estadia,1772,
deh-giulio-aleni,"Yean-sam, perto do monte chamado da Cruz, Yenp...",Giulio Aleni,morte,16490610,
deh-francisco-xavier-rosario-ho,Yuwei do Shansi,Francisco Xavier Rosario Ho,estadia,1727,
deh-germain-macret,"Zumbae, Tchamp-pa",Germain Macret,estadia,16590000,
deh-joao-barradas-ref1,rio Kan,Matteo Ricci,estadia,15940000,
deh-gottfried-xaver-von-laimbeckhoven,« Pe tsien schan »,Gottfried Xaver von Laimbeckhoven,jesuita-votos-local,17400202,
deh-adrien-grelon,"« Pe-chieh » du Sinfeng, Kiangsi",Adrien Grelon,morte,16960303,
deh-filippo-felice-carrocci,«Ponti (in valle Tellina),Filippo-Felice Carrocci,jesuita-votos-local,16850202,
deh-charles-dolze,«apud Sinas»,Charles Dolzé,jesuita-votos-local,16990202,
deh-inacio-francisco,"«in Tum cheu missionis Kim tum», au T'ong-tche...",Inácio Francisco,jesuita-votos-local,17671104,
deh-julien-placide-hervieu,À missão,Julien-Placide Hervieu,chegada,17010916,

#### Export to Excel all unlocated places

In [ ]:
filename = "../inferences/locations_names_no_wikidata.xlsx"
places_of_stay[places_of_stay['wikidata_id']=='no wikidata'][cols].sort_values(by=['place','place.date_inferred']).to_excel(filename, sheet_name='no_wikidata', index=True)

Export the list of wikidata ids for later processing by wikidata-linked-data notebook.

In [30]:
# save to csv wikidata column, except when value is "No wikidata"
filename = "../inferences/wikidata-references/locations_names_wikidata.csv"
places_of_stay[places_of_stay['wikidata_id'] != 'no wikidata']['wikidata_id'].drop_duplicates().to_csv(filename, index=False)

#### Only specific place of entry, unkown places

In [19]:
from timelink.pandas import entities_with_attribute

# Choose the place of entry
place_of_entry = 'Coimbra'

# get the ids of the places of entry
missionaries_from_place = entities_with_attribute(
    entity_type='person',
    show_elements=['name','groupname','the_line','the_order','extra_info'],
    the_type=['jesuita-entrada'],
    the_value=place_of_entry,
    db=tlnb.db,
)
print(f"Number of missionaries from {place_of_entry}: {len(missionaries_from_place)}")
place_of_entry_ids = missionaries_from_place.index
places_of_stay_specific = places_of_stay.loc[place_of_entry_ids]
places_of_stay_specific[places_of_stay_specific['wikidata_id'] == 'No wikidata'][cols].sort_values(by=['place','place.date_inferred'])

Number of missionaries from Coimbra: 63

Empty DataFrame
Columns: [place, place.type, place.attr_id, wikidata_id, place.date_inferred, place.date_inferred.formatted, groupname, name, place.comment, place.original, place.date_is_inferred, place.line, place.extra_info]
Index: []

In [20]:
places_of_stay_specific[places_of_stay_specific['wikidata_id'] == 'No wikidata'][cols].sort_values(by=['place','place.date_inferred']).to_excel(f"../inferences/jesuita_entrada_{place_of_entry}_places_of_stay_no_wikidata.xlsx", sheet_name='no_wikidata', index=True)

### Frequency of places / Frequência dos lugares

In [22]:
places_of_stay.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7180 entries, deh-abraham-le-royer to simao-rodrigues-ref1
Data columns (total 24 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   id                             7180 non-null   object
 1   name                           7180 non-null   object
 2   groupname                      7180 non-null   object
 3   the_line                       7180 non-null   int64
 4   the_order                      7180 non-null   int64
 5   extra_info                     7180 non-null   object
 6   place.attr_id                  7180 non-null   object
 7   place.type                     7180 non-null   object
 8   place                          7180 non-null   object
 9   place.date                     7180 non-null   object
 10  place.line                     7180 non-null   int64
 11  place.level                    7180 non-null   int64
 12  place.obs                      7180 non-null   object
 13  place.extra_info               7180 non-null   object
 14  place.comment                  7061 non-null   object
 15  place.original                 273 non-null    object
 16  place.date.comment             1142 non-null   object
 17  place.date.original            12 non-null     object
 18  place.obs.original             1 non-null      object
 19  id_col                         7180 non-null   object
 20  place.date_inferred            7180 non-null   object
 21  place.date_is_inferred         7180 non-null   bool
 22  wikidata_id                    7180 non-null   object
 23  place.date_inferred.formatted  7180 non-null   object
dtypes: bool(1), int64(4), object(19)
memory usage: 1.6+ MB

In [23]:
col = 'place' # subtotal by this column

# Use pandas groupby and specify unique value count for id
df_totals = places_of_stay.groupby(col).agg({'id':'nunique',
                                                'place.date_inferred':'min',
                                                'place.date':'max'})
df_totals.info()
df_totals.sort_values('id',ascending= False).head(130)

<class 'pandas.core.frame.DataFrame'>
Index: 1568 entries, 's-Hertogenbosch, Holanda to Žilina, Eslováquia
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   1568 non-null   int64
 1   place.date_inferred  1568 non-null   object
 2   place.date           1568 non-null   object
dtypes: int64(1), object(2)
memory usage: 49.0+ KB

                                      id place.date_inferred   place.date
place
Macau                                495                            >1652
Pequim                               255                        >17410115
Goa                                  209                            >1713
Cantão                               200                        >16590123
China                                186                         18050114
Lisboa                               173                         17810300
Roma                                 110                        >16851112
Coimbra                               90                        <16230324
Nanquim                               68                             1780
Paris                                 66                         17780000
Japão                                 61                         17390425
Tonquim                               59                            <1659
Índia                                 54                        <17070303
Sião                                  53                         17510000
Shanghai                              47                         17451208
Évora                                 45            15390800    <16230324
Cochinchina                           45                         17830512
Lorient                               43            17321110     17750627
Hangchow                              43                            >1636
Macau (colégio)                       39                         17580316
Malaca                                33                         17620517
Hainan                                33                      >1659:<1660
Manila                                32                        >16850206
Hukwang                               32                      >1666:<1685
Kiangsi                               31                            >1659
[No mar, a caminho da China]          30                  00     17500624
Europa                                29                            >1773
Nagasaki                              25            15830725     16430322
Filipinas                             25                            <1682
França                                24                        >17390000
Portugal                              23                         17820500
Vannes                                22                1620     16790500
Kiang-nan                             22                            >1710
Moscovo                               22                         17220609
Bordeaux                              22                         17431107
Tartária                              21                         17890000
Lisboa (Forte de S. Julião)           21                1759     17770300
Cochim                                20                         17590528
Kiangnan                              20                             1785
México                                19                        <17110700
Itália                                19                             1817
Amoy, Fukien                          18                         17000829
Génova                                17                1596     17680930
Kwangtung                             17                            >1701
Fukien                                17                         17550000
Brest                                 16             1685030     16980100
Braga                                 16                1551    <16230324
Avignon                               15                         17370927
Landsberg                             15            16230729     17770411
Nancy                                 15            16270929     17510827
Saint-Malo                            15            16370312     17301210
Lyon                                  15                         17310116
Pérsia                                14                            <1701
Nápoles                               14                         17590414
Viena                                 14            16271016     17880000
Pondichéry                            14                             1773
Cambodja                              13                             1726
Shangchuan                            13                1552     17010807
Douai                                 12                         16830109
Milão                                 12            16160614     17170000
Hou-kouang                            12                         17690108
Sungkiang                             12                             1781
Mechelen                              11            16220531     16720424
Trier                                 11            16770821     17730228
Nanchang                              11                1600         1721
Bolonha                               11              000000     17741024
Kiangchow, Shansi                     11                            >1695
Porto                                 11                  00     16890204
Honan                                 11                         17660000
Batávia                               10                         17250000
Paris (colégio Louis-le-Grand)        10                1710    >17510107
Salcete, Índia                        10                       >1640:1643
Shensi                                10                             1698
La Rochelle                           10            16420200     17090202
Moçambique                            10                         17490705
Tournai                               10            15820726     16960929
Surat                                 10                         17000202
Bruxelas                               9            16210812     16591223
Port-Louis                             9            16980221     17670315
Ningpo                                 9                1627     17480000
Madrid                                 9                         17370902
Isfahan, Pérsia                        9                         17470000
Foochow                                9                         17001121
Soochow                                9                         17590000
Kiang-si                               8                         17480128
Santarém                               8            15280000     17060202
Shiuchow (Chao-tcheou)                 8            15891000         1612
Istambul                               8                             1723
Foochow, Fukien                        8                1631   >1626:1631
Brasil                                 8                             1758
Florença                               8                         17340502
Marseille                              8            16670321     17250104
Fatshan                                7                         17630000
Toulouse                               7                            >1642
Shansi                                 7                         17181020
Agra                                   7                            <1663
Palermo                                7                1572     16561022
Kiangchow                              7                         17310800
Goa (casa professa)                    7            16500325     17400000
Tchö-kiang                             7            16171002        >1710
Concépcion, Chile                      7            17040513     17110000
Poitiers                               7                         16930000
Macau (colégio de S. José)             7                1732     17620705
Madurai                                7                         17141102
Rouen                                  7                         16700301
Chennai, Índia                         7                         16990708
Alcalá                                 7            15550925         1690
Esmirna, Pérsia                        6                             1695
[No mar, a caminho da Índia]           6            16440502     17421200
[No mar, a caminho de Lisboa]          6                         17640512
Molucas                                6                            <1623
Leuven                                 6                         16571209
Shantung                               6                             1711
Turim                                  6                         17170000
Antuérpia                              6            16401115     17220106
Kiangchow, Chan-si                     6            16241200     16960000
Cracóvia                               6                1610     17140727
Munique                                6                         17100117
Mysore                                 6                             1754
Pont-à-Mousson                         6            15920000     17580202
[Missão]                               6                1645         1754
Brno                                   6            16060000     17261009
Viana do Alentejo, diocese de Évora    6                1596         1635
Paris (colégio de La Flèche)           6                        >17510107
Castel Gandolfo                        6            17641010     17711201
Bengala                                6                1576        >1661
Leao-tong                              6                         17430000
Kwangsi                                6                             1696
Londres                                6            17031004     17050000
Arménia                                6                            >1689

In [24]:
# export totals to excel
df_totals.sort_values('id',ascending= False).to_excel(f"../inferences/locations_totals.xlsx", sheet_name='totals', index=True)

### Who was at a specific place


List those who stayed at a specific place

In [25]:
place="Coimbra"

In [26]:
cols = ['place','name','place.type','place.date_inferred','place.obs']
show_only=100
places_of_stay[places_of_stay.place==place][cols].sort_values(by=['place.date_inferred']).head(show_only)

,place,name,place.type,place.date_inferred,place.obs
id_col,,,,,
deh-nicolas-trigault,Coimbra,Nicolas Trigault,estadia-x,,
deh-bartolomeo-tedeschi,Coimbra,Bartolomeo Tedeschi,estadia-x,,
deh-belchior-miguel-carneiro-leitao,Coimbra,Belchior Miguel Carneiro Leitão,nascimento,1519,
deh-pedro-de-alcacova,Coimbra,Pedro de Alcáçova,jesuita-entrada,15420000,saiu a primeira vez
deh-pedro-martins,Coimbra,Pedro Martins,nascimento,15420000,
deh-belchior-nunes-barreto,Coimbra,Belchior Nunes Barreto,jesuita-entrada,15430311,
deh-belchior-miguel-carneiro-leitao,Coimbra,Belchior Miguel Carneiro Leitão,jesuita-entrada,15430425,
deh-francisco-perez,Coimbra,Francisco Pérez,jesuita-entrada,15440125,
deh-tiburcio-de-quadros,Coimbra,Tibúrcio de Quadros,jesuita-entrada,15440418,
deh-goncalo-alvares,Coimbra,Gonçalo Álvares,jesuita-entrada,15490101,
deh-cristovao-da-costa,Coimbra,Cristóvão da Costa,jesuita-entrada,15500103,
deh-joao-rodrigues-de-sainan,Coimbra,João Rodrigues de Sainan,jesuita-entrada,1555,
deh-pedro-martins,Coimbra,Pedro Martins,jesuita-entrada,15560525,
deh-lourenco-mexia,Coimbra,Lourenço Mexia,jesuita-entrada,15600314,
deh-goncalo-alvares,Coimbra,Gonçalo Álvares,jesuita-votos-local,15600609,
deh-nicolau-pimenta,Coimbra,Nicolau Pimenta,jesuita-entrada,15620502,
deh-lourenco-mexia,Coimbra,Lourenço Mexia,jesuita-votos-local,15700423,
deh-pedro-ramon,Coimbra,Pedro Ramón,jesuita-ordenacao-padre,1573,
deh-francisco-vieira,Coimbra,Francisco Vieira,jesuita-entrada,15740200,
deh-manuel-gaspar,Coimbra,Manuel Gaspar,jesuita-entrada,15750926,
deh-antonio-de-abreu-ref1,Coimbra,António de Abreu,jesuita-entrada,15760000,
deh-antonio-de-almeida,Coimbra,António de Almeida,jesuita-entrada,15760104,
deh-joao-rodrigues-girao,Coimbra,João Rodrigues Girão,jesuita-entrada,15761216,
deh-duarte-de-sande,Coimbra,Duarte de Sande,jesuita-ordenacao-padre,1577,
deh-matteo-ricci,Coimbra,Matteo Ricci,estadia-x,15770600,"""""""\n Ricci and Tacchi Ventur..."
deh-joao-da-rocha,Coimbra,João da Rocha,jesuita-entrada,1583,Corrigido: local de entrada
deh-mateus-de-couros,Coimbra,Mateus de Couros,jesuita-entrada,15831222,
deh-joao-soeiro,Coimbra,João Soeiro,jesuita-entrada,1584,
deh-diogo-correia-valente,Coimbra,Diogo Correia Valente,jesuita-entrada,15840110,
deh-andre-palmeiro,Coimbra,André Palmeiro,jesuita-entrada,15840114,
deh-francisco-pacheco,Coimbra,Francisco Pacheco,jesuita-entrada,15860000,
deh-simao-da-cunha,Coimbra,Simão da Cunha,nascimento,1589,
deh-gaspar-ferreira,Coimbra,Gaspar Ferreira,jesuita-entrada,15890300,
deh-sebastiao-fernandes,Coimbra,Sebastião Fernandes,jesuita-entrada,1591,
deh-pero-rodrigues-ref1,Coimbra,Pero Rodrigues,jesuita-votos-local,15910113,
deh-sebastiao-vieira,Coimbra,Sebastião Vieira,jesuita-entrada,15910203,
deh-manuel-dias-o-novo,Coimbra,"Manuel Dias, o Novo",jesuita-entrada,15930202,
deh-feliciano-da-silva,Coimbra,Feliciano da Silva,jesuita-entrada,15931215,
deh-antonio-de-andrade,Coimbra,António de Andrade,jesuita-entrada,15961216,
deh-inacio-lobo,Coimbra,Inácio Lobo,nascimento,1603,
deh-andre-palmeiro,Coimbra,André Palmeiro,jesuita-votos-local,16030727,
deh-simao-da-cunha,Coimbra,Simão da Cunha,jesuita-entrada,16060113,
deh-manuel-rodrigues-ii-ref3,Coimbra,Manuel Rodrigues,nascimento,1607,
deh-antonio-de-gouvea,Coimbra,António de Gouveia,jesuita-entrada,16080502,
deh-gaspar-do-amaral,Coimbra,Gaspar do Amaral,jesuita-entrada,16080601,
deh-francisco-furtado,Coimbra,Francisco Furtado,jesuita-entrada,1610,
deh-sebastiao-da-maia,Coimbra,Sebastião da Maia,jesuita-entrada,16110000,
deh-gaspar-luis,Coimbra,Gaspar Luís,estadia-x,1616,
deh-gaspar-luis,Coimbra,Gaspar Luís,estadia-x,1618,
deh-manuel-jorge,Coimbra,Manuel Jorge,nascimento,16210000,
deh-gabriel-de-magalhaes,Coimbra,Gabriel de Magalhães,jesuita-entrada,16250000,
deh-manuel-de-pereira-ref2,Coimbra,Manuel Pereira,nascimento,16290000,
deh-matias-da-maia,Coimbra,Matias da Maia,jesuita-entrada,16290510,
deh-goncalo-da-fonseca,Coimbra,Gonçalo da Fonseca,jesuita-entrada,1634,
deh-adriano-pestana,Coimbra,Adriano Pestana,jesuita-entrada,16350000,
deh-manuel-jorge,Coimbra,Manuel Jorge,jesuita-entrada,16380000,
deh-andre-ferrao,Coimbra,André Ferrão,jesuita-entrada,1640,"[Brockey diz ""educated at the College of Coimb..."
deh-adriano-pestana,Coimbra,Adriano Pestana,estadia-x,1640-08-26,
deh-afonso-aires,Coimbra,Afonso Aires,jesuita-entrada,16490000,
deh-afonso-aires-ref1,Coimbra,Aires de Almeida,estadia,16490000,
deh-tome-pereira,Coimbra,Tomé (Sancho) Pereira,jesuita-entrada,16610925,
deh-manuel-de-siqueira-tcheng,Coimbra,Manuel de Siqueira Tcheng,jesuita-ordenacao-padre,1664,
deh-andre-carneiro,Coimbra,André Carneiro,jesuita-entrada,16640325,
deh-joao-da-silva,Coimbra,João da Silva,jesuita-entrada,1668,
deh-antonio-da-silva,Coimbra,António da Silva,jesuita-entrada,16690319,
deh-antonio-lopes-junior,Coimbra,"António Lopes, júnior",nascimento,16690500,
deh-adam-algenler,Coimbra,Adam Algenler,estadia-x,16720400:16739100,"Golvers, 2019"
deh-manuel-mendes,Coimbra,Manuel Mendes,jesuita-entrada,16730315,
deh-matias-rodrigues,Coimbra,Matias Rodrigues,nascimento,1675,
deh-manuel-de-sa,Coimbra,Manuel de Sá,jesuita-entrada,16750213,
deh-francisco-pinto-i,Coimbra,Francisco Pinto,jesuita-entrada,16770527,
deh-miguel-do-amaral,Coimbra,Miguel do Amaral,jesuita-entrada,16770701,
deh-antoine-thomas,Coimbra,Antoine Thomas,estadia-x,1678000,"""""""\n Fiolhais and Franco, 2016, O..."
deh-manuel-osorio-i,Coimbra,Manuel Osório,jesuita-entrada,16780215,
deh-adam-weidenfied,Coimbra,Adam Weidenfied,estadia,16791218,
deh-joachim-calmes,Coimbra,Joachim Calmes,estadia-x,16810106,
deh-estanislau-machado,Coimbra,Estanislau Machado,jesuita-entrada,16810515,
deh-antonio-lopes-junior,Coimbra,"António Lopes, júnior",jesuita-entrada,16841225,
deh-leonardo-teixeira,Coimbra,Leonardo Teixeira,jesuita-entrada,16860303,
deh-antonio-da-silva,Coimbra,António da Silva,jesuita-votos-local,16870815,
deh-francisco-moreira,Coimbra,Francisco Moreira,nascimento,16891227,
deh-estevao-collasco,Coimbra,Estêvão Collasco,jesuita-entrada,16920127,
deh-antonio-de-magalhaes,Coimbra,António de Magalhães,jesuita-entrada,16921019,
deh-inacio-lopes,Coimbra,Inácio Lopes,estadia,1693,no primeiro ano de Teologia
deh-antao-dantas,Coimbra,Antão Dantas,jesuita-entrada,16930310,
deh-manuel-ribeiro-senior,Coimbra,"Manuel Ribeiro, sénior",jesuita-entrada,16931030,
deh-matias-rodrigues,Coimbra,Matias Rodrigues,jesuita-entrada,16940130,
deh-policarpo-de-sousa,Coimbra,Policarpo de Sousa,nascimento,16970126,
deh-manuel-de-silva-ref1,Coimbra,Manuel de Silva,nascimento,16971213,
deh-antonio-de-melo,Coimbra,António de Melo,jesuita-entrada,16990424,
deh-luis-de-caldas,Coimbra,Luís de Caldas,jesuita-entrada,17041224,
deh-jose-montanha-ii,Coimbra,José Montanha,nascimento,17080103,
deh-estevao-lopes,Coimbra,Estêvão Lopes,jesuita-entrada,17080321,
deh-giuseppe-castiglione,Coimbra,Giuseppe Castiglione,estadia,1709,
deh-xavier-duarte,Coimbra,Xavier Duarte,nascimento,17141111,
deh-bento-monteiro,Coimbra,Bento Monteiro,nascimento,17180601,
deh-bento-ferreira,Coimbra,Bento Ferreira,nascimento,17210501,
deh-jose-montanha-ii,Coimbra,José Montanha,jesuita-entrada,17211031,
deh-antonio-gomes,Coimbra,António Gomes,jesuita-entrada,17250528,
deh-joaquim-de-azevedo,Coimbra,Joaquim de Azevedo,nascimento,17300922,

#### Export to markdown

In [27]:
places_of_stay.itertuples(index=True)

In [28]:
import os
from pandas import DataFrame
from timelink.pandas import group_attributes as person_attributes

# create if it does not exist directory ../inferences/{place_of_entry}/markdown"
directory = f"../inferences/{place_of_entry}/markdown"
if not os.path.exists(directory):
    os.makedirs(directory)


for id, name in places_of_stay[places_of_stay.place==place][['name']].sort_values('name').itertuples(index=True):
    with tlnb.db.session() as session:
        p = tlnb.db.get_person(id, session=session)
        session.add(p)
        pk:str = p.to_kleio()
        pk = f"""## {name}
^[In Edit mode, select title (including the ##), right click and "Extract selection"]

---
### {name} @ timelink
```
{pk}
```

---
Select title, right click on selected title, choose extract note
"""
        fname = f"{directory}/{id}.md"
        with open(fname, 'w', encoding='utf-8') as f:
            f.write(pk)